// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use Vercel's pooled connection for Prisma, with multiple fallbacks
    // For migrations, prefer non-pooling URL
    // Uses placeholder for builds without database access (prisma generate only)
    url: process.env.POSTGRES_URL || process.env.POSTGRES_URL_NON_POOLING || process.env.POSTGRES_PRISMA_URL || process.env.POSTGRES_URL || "postgresql://placeholder",
  },
});
