// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use Vercel's pooled connection for Prisma, fallback to DATABASE_URL
    url: env("POSTGRES_PRISMA_URL") ?? env("POSTGRES_URL"),
  },
});
