// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import * as dotenv from "dotenv";
import { resolve } from "path";
import { defineConfig } from "prisma/config";

// Load environment variables from .env.local (Next.js convention)
dotenv.config({ path: resolve(process.cwd(), ".env.local") });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use DATABASE_URL (matches Prisma client configuration in lib/db/prisma.ts)
    // Falls back to Vercel's pooled connections, then placeholder for builds
    url: process.env.DATABASE_URL || process.env.POSTGRES_PRISMA_URL || process.env.POSTGRES_URL || "postgresql://placeholder",
  },
});
